arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_pan_joint
    - elbow_lift_joint
    - wrist_pan_joint
    - wrist_lift_joint
  gains:
    shoulder_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_pan_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_lift_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - gripper_left_joint
    - gripper_right_joint
  gains:
    gripper_left_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    gripper_right_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
head_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_camera_pan
    - joint_camera_tilt
  gains:
    joint_camera_pan:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_camera_tilt:
      p: 100
      d: 1
      i: 1
      i_clamp: 1