sensors:
  - filtered_cloud_topic: filtered_cloud
    max_range: 1.5
    max_update_rate: 0.5
    padding_offset: 0.1
    padding_scale: 1.0
    point_cloud_topic: /zed_node/point_cloud/cloud_registered
    point_subsample: 1
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater