sensors:
  - filtered_cloud_topic: filtered_cloud
    max_range: 1.0
    max_update_rate: 0.45
    padding_offset: 0.1
    padding_scale: 2.0
    point_cloud_topic: /camera/depth_registered/points
    point_subsample: 1
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
